name = "ResSimAD"
uuid = "0f5291bf-5850-40d8-bc7e-2ce68032ef0b"
authors = ["Yimin Liu"]
version = "0.1.0"

[compat]
julia = "1.4.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
